// import & define all of icons & images uses in prj here

export const images = {
    splashshape: require("../../assets/splashshape.png"),
    logo: require("../../assets/logo.png"),
    eye: require("../assets/eye.png"),
    noneye: require("../assets/noneye.png"),
    loginbg:require("../../assets/loginbg.png"),
    mblogo:require("../../assets/mblogo.png"),
    avatar: require('../../assets/avatar.jpg'),
    home: require('../../assets/home.png'),
    user: require('../../assets/user.png'),
    logout: require('../../assets/logout.png'),
    back:require("../../assets/backicon.png"),
    AVGIncome: require("../assets/AVGIncome.png"),
    KPImonthreport: require("../assets/KPImonthreport.png"),
    planfollow: require("../assets/planfollow.png"),
    salarybymonth: require("../assets/salarybymonth.png"),
    subscriberquality: require("../assets/subscriberquality.png"),
    warning: require("../assets/warning.png"),
    productivitysub: require("../assets/productivitysub.png"),
    deliveringenterprise: require("../assets/deliveringenterprise.png"),
    executeplan: require("../assets/executeplan.png"),
    fixedwage: require("../assets/fixedwage.png"),
    others: require("../assets/others.png"),
    planout: require("../assets/planout.png"),
    product: require("../assets/product.png"),
    sanctions: require("../assets/sanctions.png"),

    contractdebt: require("../assets/ic_contractdebt.png"),
    debtPercent: require("../assets/ic_debtPercent.png"),
    denyTwoC: require("../assets/ic_denyTwoC.png"),
    newSubPrePaid: require("../assets/ic_newSubPrePaid.png"),
    preToPostPaid: require("../assets/ic_preToPostPaid.png"),
    revokeAmount: require("../assets/ic_revokeAmount.png"),
    totalDebtNinety: require("../assets/ic_totalDebtNinety.png"),
    totalRevenue: require("../assets/ic_totalRevenue.png"),

    enterprisefluct: require("../assets/enterprisefluct.png"),
    incomefluct: require("../assets/incomefluct.png"),
    subfluct: require("../assets/subfluct.png"),

    growthTotal: require("../assets/growthTotal.png"),
    newSubTotal: require("../assets/newSubTotal.png"),
    totalKPI: require("../assets/totalKPI.png"),
    totalOTarget: require("../assets/totalOTarget.png"),

    change4Gsim: require("../assets/change4Gsim.png"),
    growthenterprise: require("../assets/growthenterprise.png"),
    incurredrevenue: require("../assets/incurredrevenue.png"),
    qualitysub: require("../assets/qualitysub.png"),
    retailrevenue: require("../assets/retailrevenue.png"),
    telecommunicationrevenue: require("../assets/telecommunicationrevenue.png"),
    totalpostpaid: require("../assets/totalpostpaid.png"),

}